name: "Build"

on: 
  push:
    branches: '**'

jobs:
  build-job:
    runs-on: ubuntu-latest
    name: "Build and test"

    steps:
    - name: "Setup node"
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: "Checkout source code"
      uses: "actions/checkout@v2"
    - name: "Install modules"
      run: "npm ci"
    - name: "Build (npm)"
      run: "npm run build"
    - name: "Test"
      run: "npm test"
